name: Test Action
on:
  pull_request

jobs:
  compare_packages:
    name: Compare packages to main using GH action
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v1
      - name: List packges before and after 
        id: list_packages
        shell: bash
        run: |
          git checkout main
          dotnet restore
          dotnet list package --include-transitive > packages-before.txt

          git checkout -
          dotnet restore
          dotnet list package --include-transitive > packages-after.txt
